from typing import Any, Protocol


class RecibosRepository(Protocol):
    def stats_ventas(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_metodos_pago(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_ventas(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_venta(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_venta(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancelar_venta(self, *args: Any, **kwargs: Any) -> Any: ...
