from typing import Any, Protocol


class DoctoresRepository(Protocol):
    def doctor_del_dia(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_doctores(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_disponibilidad_semana(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_doctor(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_doctor(self, *args: Any, **kwargs: Any) -> Any: ...
    def actualizar_doctor(self, *args: Any, **kwargs: Any) -> Any: ...
    def desactivar_doctor(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_disponibilidad(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_disponibilidad(self, *args: Any, **kwargs: Any) -> Any: ...
    def eliminar_disponibilidad(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_servicios_doctor(self, *args: Any, **kwargs: Any) -> Any: ...
