from typing import Any, Protocol


class PreregistroRepository(Protocol):
    def listar_preregistros(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_preregistro(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_tipos_espina_publico(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_tipos_documento_publico(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_preregistro(self, *args: Any, **kwargs: Any) -> Any: ...
    def actualizar_preregistro(self, *args: Any, **kwargs: Any) -> Any: ...
    def aprobar_preregistro(self, *args: Any, **kwargs: Any) -> Any: ...
    async def subir_documento(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_documentos(self, *args: Any, **kwargs: Any) -> Any: ...
    def eliminar_documento(self, *args: Any, **kwargs: Any) -> Any: ...
    def rechazar_preregistro(self, *args: Any, **kwargs: Any) -> Any: ...
