from typing import Any, Protocol


class ReportesRepository(Protocol):
    def reporte_por_genero(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_por_etapa_vida(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_por_tipo_espina(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_por_estado(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_resumen(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_servicios_por_tipo(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_estudios_por_tipo(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_pagos_exentos(self, *args: Any, **kwargs: Any) -> Any: ...
    def reporte_consolidado_mensual(self, *args: Any, **kwargs: Any) -> Any: ...
    def historial_reportes(self, *args: Any, **kwargs: Any) -> Any: ...
