from typing import Any, Protocol


class ExportacionesRepository(Protocol):
    def exportar_reporte_pdf(self, *args: Any, **kwargs: Any) -> Any: ...
    def exportar_beneficiario_pdf(self, *args: Any, **kwargs: Any) -> Any: ...
    def exportar_credencial_pdf(self, *args: Any, **kwargs: Any) -> Any: ...
    def exportar_comprobante_cita(self, *args: Any, **kwargs: Any) -> Any: ...
    def exportar_contrato_comodato(self, *args: Any, **kwargs: Any) -> Any: ...
    def exportar_beneficiarios_excel(self, *args: Any, **kwargs: Any) -> Any: ...
    def exportar_reporte_excel(self, *args: Any, **kwargs: Any) -> Any: ...
