-- ============================================================================
-- Migration 002 — Triggers
-- Fecha: 2026-04-14
--   0. Relajar BITACORA_CAMBIOS.ID_USUARIO a NULL (el autor puede no estar
--      disponible si el cambio ocurre fuera de una sesión con
--      CLIENT_IDENTIFIER fijado, p.ej. jobs o DDL).
--   1. TRG_VENTA_FOLIO_BI   — BEFORE INSERT ON VENTA. Autogenera FOLIO
--      tipo 'REC-YYYY-NNNNNN' si viene NULL.
--   2. TRG_BITACORA_USUARIO_AIUD — AFTER INSERT/UPDATE/DELETE ON USUARIO_SISTEMA.
--      Registra en BITACORA_CAMBIOS los cambios de ROL, ESTATUS, CORREO y
--      altas/bajas. El ID_USUARIO autor se obtiene de
--      SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER') (fijado por el middleware
--      FastAPI con DBMS_SESSION.SET_IDENTIFIER).
-- ============================================================================

ALTER TABLE BITACORA_CAMBIOS MODIFY (ID_USUARIO NUMBER NULL);

CREATE OR REPLACE TRIGGER TRG_VENTA_FOLIO_BI
BEFORE INSERT ON VENTA
FOR EACH ROW
BEGIN
  IF :NEW.FOLIO_VENTA IS NULL THEN
    :NEW.FOLIO_VENTA := 'REC-' || TO_CHAR(SYSDATE, 'YYYY') || '-' ||
                        LPAD(SEQ_VENTA_FOLIO.NEXTVAL, 6, '0');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BITACORA_USUARIO_AIUD
AFTER INSERT OR UPDATE OR DELETE ON USUARIO_SISTEMA
FOR EACH ROW
DECLARE
  v_id_autor NUMBER;
  v_ident    VARCHAR2(64);
BEGIN
  v_ident := SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER');
  BEGIN
    v_id_autor := TO_NUMBER(v_ident);
  EXCEPTION WHEN OTHERS THEN
    v_id_autor := NULL;
  END;

  IF INSERTING THEN
    INSERT INTO BITACORA_CAMBIOS (
      TABLA_AFECTADA, ID_REGISTRO_AFECTADO, CAMPO_MODIFICADO,
      VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION,
      ID_USUARIO, FECHA_CAMBIO, OBSERVACIONES
    ) VALUES (
      'USUARIO_SISTEMA', :NEW.ID_USUARIO, NULL,
      NULL, :NEW.CORREO, 'INSERT',
      v_id_autor, SYSTIMESTAMP, 'Alta de usuario'
    );

  ELSIF UPDATING THEN
    IF NVL(:OLD.ROL, '~') <> NVL(:NEW.ROL, '~') THEN
      INSERT INTO BITACORA_CAMBIOS (
        TABLA_AFECTADA, ID_REGISTRO_AFECTADO, CAMPO_MODIFICADO,
        VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION,
        ID_USUARIO, FECHA_CAMBIO, OBSERVACIONES
      ) VALUES (
        'USUARIO_SISTEMA', :NEW.ID_USUARIO, 'ROL',
        :OLD.ROL, :NEW.ROL, 'UPDATE',
        v_id_autor, SYSTIMESTAMP, NULL
      );
    END IF;

    IF NVL(:OLD.ESTATUS, '~') <> NVL(:NEW.ESTATUS, '~') THEN
      INSERT INTO BITACORA_CAMBIOS (
        TABLA_AFECTADA, ID_REGISTRO_AFECTADO, CAMPO_MODIFICADO,
        VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION,
        ID_USUARIO, FECHA_CAMBIO, OBSERVACIONES
      ) VALUES (
        'USUARIO_SISTEMA', :NEW.ID_USUARIO, 'ESTATUS',
        :OLD.ESTATUS, :NEW.ESTATUS, 'UPDATE',
        v_id_autor, SYSTIMESTAMP, NULL
      );
    END IF;

    IF NVL(:OLD.CORREO, '~') <> NVL(:NEW.CORREO, '~') THEN
      INSERT INTO BITACORA_CAMBIOS (
        TABLA_AFECTADA, ID_REGISTRO_AFECTADO, CAMPO_MODIFICADO,
        VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION,
        ID_USUARIO, FECHA_CAMBIO, OBSERVACIONES
      ) VALUES (
        'USUARIO_SISTEMA', :NEW.ID_USUARIO, 'CORREO',
        :OLD.CORREO, :NEW.CORREO, 'UPDATE',
        v_id_autor, SYSTIMESTAMP, NULL
      );
    END IF;

  ELSIF DELETING THEN
    INSERT INTO BITACORA_CAMBIOS (
      TABLA_AFECTADA, ID_REGISTRO_AFECTADO, CAMPO_MODIFICADO,
      VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION,
      ID_USUARIO, FECHA_CAMBIO, OBSERVACIONES
    ) VALUES (
      'USUARIO_SISTEMA', :OLD.ID_USUARIO, NULL,
      :OLD.CORREO, NULL, 'DELETE',
      v_id_autor, SYSTIMESTAMP, 'Baja de usuario'
    );
  END IF;
END;
/
