-- Add CATEGORIA column to SERVICIO table to distinguish regular services from lab studies
ALTER TABLE SERVICIO ADD (CATEGORIA VARCHAR2(50) DEFAULT 'SERVICIO' NOT NULL);

ALTER TABLE SERVICIO ADD CONSTRAINT CHK_SERVICIO_CATEGORIA
  CHECK (CATEGORIA IN ('SERVICIO', 'LABORATORIO'));

COMMIT;
