-- ============================================================================
-- Migration 022 — Foreign keys faltantes del schema original
-- Fecha: 2026-06-03
-- Objetivo: agregar todas las FK constraints que no se declararon al crear
--   el schema inicial, para que el diagrama ER refleje las relaciones reales
--   y Oracle pueda validar integridad referencial.
-- Pre-requisito: todos los registros existentes son consistentes (verificado).
-- ============================================================================

-- DISPONIBILIDAD_DOCTOR
ALTER TABLE DISPONIBILIDAD_DOCTOR
  ADD CONSTRAINT FK_DISP_DOC_DOCTOR
  FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR);

-- DOCUMENTO_PACIENTE
ALTER TABLE DOCUMENTO_PACIENTE
  ADD CONSTRAINT FK_DOCPAC_PACIENTE
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE DOCUMENTO_PACIENTE
  ADD CONSTRAINT FK_DOCPAC_TIPO_DOC
  FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO);

ALTER TABLE DOCUMENTO_PACIENTE
  ADD CONSTRAINT FK_DOCPAC_USUARIO
  FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES USUARIO_SISTEMA(ID_USUARIO);

-- EQUIPO_MEDICO (subtipo de PRODUCTO — su PK es también FK)
ALTER TABLE EQUIPO_MEDICO
  ADD CONSTRAINT FK_EQUIPO_PRODUCTO
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);

-- EXISTENCIA_PRODUCTO
ALTER TABLE EXISTENCIA_PRODUCTO
  ADD CONSTRAINT FK_EXISTENCIA_PRODUCTO
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);

-- MEDICAMENTO (subtipo de PRODUCTO — su PK es también FK)
ALTER TABLE MEDICAMENTO
  ADD CONSTRAINT FK_MEDICAMENTO_PRODUCTO
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);

-- CITA
ALTER TABLE CITA
  ADD CONSTRAINT FK_CITA_PACIENTE
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE CITA
  ADD CONSTRAINT FK_CITA_USUARIO
  FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES USUARIO_SISTEMA(ID_USUARIO);

-- COMODATO
ALTER TABLE COMODATO
  ADD CONSTRAINT FK_COMODATO_PACIENTE
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE COMODATO
  ADD CONSTRAINT FK_COMODATO_EQUIPO
  FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO_MEDICO(ID_PRODUCTO);

ALTER TABLE COMODATO
  ADD CONSTRAINT FK_COMODATO_USUARIO
  FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES USUARIO_SISTEMA(ID_USUARIO);

-- DETALLE_CITA_SERVICIO (FK_DETCITA_DOCTOR de migración 001 nunca se aplicó)
ALTER TABLE DETALLE_CITA_SERVICIO
  ADD CONSTRAINT FK_DETCITA_DOCTOR
  FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR);

ALTER TABLE DETALLE_CITA_SERVICIO
  ADD CONSTRAINT FK_DETCITA_SERVICIO
  FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO);

ALTER TABLE DETALLE_CITA_SERVICIO
  ADD CONSTRAINT FK_DETCITA_VENTA
  FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA);

-- DOCTOR_SERVICIO
ALTER TABLE DOCTOR_SERVICIO
  ADD CONSTRAINT FK_DS_SERVICIO
  FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO);

-- MOVIMIENTO_INVENTARIO
ALTER TABLE MOVIMIENTO_INVENTARIO
  ADD CONSTRAINT FK_MOV_PRODUCTO
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);

ALTER TABLE MOVIMIENTO_INVENTARIO
  ADD CONSTRAINT FK_MOV_USUARIO
  FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES USUARIO_SISTEMA(ID_USUARIO);

ALTER TABLE MOVIMIENTO_INVENTARIO
  ADD CONSTRAINT FK_MOV_VENTA
  FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA);

-- PACIENTE_TIPO_ESPINA
ALTER TABLE PACIENTE_TIPO_ESPINA
  ADD CONSTRAINT FK_PTE_TIPO_ESPINA
  FOREIGN KEY (ID_TIPO_ESPINA) REFERENCES TIPO_ESPINA_BIFIDA(ID_TIPO_ESPINA);

-- REPORTE
ALTER TABLE REPORTE
  ADD CONSTRAINT FK_REPORTE_USUARIO
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO_SISTEMA(ID_USUARIO);

-- BITACORA_CAMBIOS (ID_USUARIO nullable — registro puede ser de sistema)
ALTER TABLE BITACORA_CAMBIOS
  ADD CONSTRAINT FK_BITACORA_USUARIO
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO_SISTEMA(ID_USUARIO);
