-- Eliminar productos variante (ID_PRODUCTO_PADRE NOT NULL) y sus registros dependientes.
-- La feature de variantes fue removida; estos registros son huérfanos funcionales.

-- 1. Bitácora (registros de auditoría de las variantes)
DELETE FROM BITACORA_CAMBIOS
WHERE TABLA_AFECTADA = 'PRODUCTO'
  AND ID_REGISTRO_AFECTADO IN (
      SELECT ID_PRODUCTO FROM PRODUCTO WHERE ID_PRODUCTO_PADRE IS NOT NULL
  );

-- 2. Movimientos de inventario asociados a variantes
DELETE FROM MOVIMIENTO_INVENTARIO
WHERE ID_PRODUCTO IN (
    SELECT ID_PRODUCTO FROM PRODUCTO WHERE ID_PRODUCTO_PADRE IS NOT NULL
);

-- 3. Existencia
DELETE FROM EXISTENCIA_PRODUCTO
WHERE ID_PRODUCTO IN (
    SELECT ID_PRODUCTO FROM PRODUCTO WHERE ID_PRODUCTO_PADRE IS NOT NULL
);

-- 4. Registro en MEDICAMENTO (las variantes sólo podían ser MEDICAMENTO)
DELETE FROM MEDICAMENTO
WHERE ID_PRODUCTO IN (
    SELECT ID_PRODUCTO FROM PRODUCTO WHERE ID_PRODUCTO_PADRE IS NOT NULL
);

-- 5. Registro en EQUIPO_MEDICO (por si acaso)
DELETE FROM EQUIPO_MEDICO
WHERE ID_PRODUCTO IN (
    SELECT ID_PRODUCTO FROM PRODUCTO WHERE ID_PRODUCTO_PADRE IS NOT NULL
);

-- 6. Por último, eliminar los productos variante en sí
DELETE FROM PRODUCTO WHERE ID_PRODUCTO_PADRE IS NOT NULL;

COMMIT;
