from typing import Any, Protocol


class BeneficiariosRepository(Protocol):
    def listar_tipos_espina(self, *args: Any, **kwargs: Any) -> Any: ...
    def stats_beneficiarios(self, *args: Any, **kwargs: Any) -> Any: ...
    def dashboard_stats(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_beneficiarios(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_beneficiario(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_beneficiario(self, *args: Any, **kwargs: Any) -> Any: ...
    def actualizar_beneficiario(self, *args: Any, **kwargs: Any) -> Any: ...
    def eliminar_beneficiario(self, *args: Any, **kwargs: Any) -> Any: ...
    def historial_beneficiario(self, *args: Any, **kwargs: Any) -> Any: ...
