from typing import Any, Protocol


class CitasRepository(Protocol):
    def citas_stats(self, *args: Any, **kwargs: Any) -> Any: ...
    def citas_hoy(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_citas(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_cita(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_cita(self, *args: Any, **kwargs: Any) -> Any: ...
    def actualizar_cita(self, *args: Any, **kwargs: Any) -> Any: ...
    def completar_cita(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancelar_cita(self, *args: Any, **kwargs: Any) -> Any: ...
    def eliminar_cita(self, *args: Any, **kwargs: Any) -> Any: ...
