from typing import Any, Optional, Protocol


class CitasRepository(Protocol):
    def citas_stats(self, current_user: dict | None = None) -> dict: ...

    def citas_hoy(self, current_user: dict | None = None) -> list[dict]: ...

    def listar_citas(
        self,
        fecha: Optional[str] = None,
        estatus: Optional[str] = None,
        id_paciente: Optional[int] = None,
        busqueda: Optional[str] = None,
        current_user: dict | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[dict]: ...

    def obtener_cita(self, id_cita: int, current_user: dict | None = None) -> dict: ...

    def crear_cita(self, data: Any, current_user: dict | None = None) -> dict: ...

    def actualizar_cita(self, id_cita: int, data: Any, current_user: dict | None = None) -> dict: ...

    def completar_cita(self, id_cita: int, current_user: dict | None = None) -> dict: ...

    def cancelar_cita(self, id_cita: int, current_user: dict | None = None) -> dict: ...

    def eliminar_cita(self, id_cita: int, current_user: dict | None = None) -> None: ...

    def citas_proximas(self, dias: int = 7, current_user: dict | None = None) -> list[dict]: ...
