from typing import Any, Protocol


class AlmacenRepository(Protocol):
    def listar_productos(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_producto(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_producto(self, *args: Any, **kwargs: Any) -> Any: ...
    def actualizar_producto(self, *args: Any, **kwargs: Any) -> Any: ...
    def desactivar_producto(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_servicios(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_servicio(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_servicio(self, *args: Any, **kwargs: Any) -> Any: ...
    def actualizar_servicio(self, *args: Any, **kwargs: Any) -> Any: ...
    def desactivar_servicio(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_comodatos(self, *args: Any, **kwargs: Any) -> Any: ...
    def obtener_comodato(self, *args: Any, **kwargs: Any) -> Any: ...
    def crear_comodato(self, *args: Any, **kwargs: Any) -> Any: ...
    def actualizar_comodato(self, *args: Any, **kwargs: Any) -> Any: ...
    def listar_movimientos(self, *args: Any, **kwargs: Any) -> Any: ...
    def almacen_stats(self, *args: Any, **kwargs: Any) -> Any: ...
